#!/usr/bin/env python3

from pykalman import KalmanFilter
import numpy as np
import matplotlib.pyplot as plt
import time

import rospy
from sensor_msgs.msg import Imu

AccX_Value = 0
AccX_Variance = 0.05
rosrate = 6.
AccX_ValueImu1, g1 = 0, [0,0,0]
AccX_ValueImu2, g2 = 0, [0,0,0]

def _callback_imu_data(msg):
  global AccX_ValueData, orientation
  AccX_ValueData = msg.linear_acceleration.x
  orientation = msg.orientation

def _callback_imu_1(msg):
  global AccX_ValueImu1, g1
  AccX_ValueImu1 = msg.linear_acceleration.x
  g1 = msg.linear_acceleration

  
def _callback_imu_2(msg):
  global AccX_ValueImu2, g2
  AccX_ValueImu2 = msg.linear_acceleration.x
  g2 = msg.linear_acceleration

rospy.init_node('imu_kalman', anonymous=True)
rospy.Subscriber('/BlueRov2/imu/data', Imu, _callback_imu_data)
rospy.Subscriber('/BlueRov2/imu/imu1', Imu, _callback_imu_1)
rospy.Subscriber('/BlueRov2/imu/imu2', Imu, _callback_imu_2)
rate = rospy.Rate(rosrate)


AccX_Value = (AccX_ValueImu1+AccX_ValueImu2)/2.

# compensate the accelerometer readings from gravity. 
# @param q the quaternion representing the orientation of a 9DOM MARG sensor array
# @param acc the readings coming from an accelerometer expressed in g
#
# @return a 3d vector representing dinamic acceleration expressed in g
def gravity_compensate(q, acc):
  g = [0.0, 0.0, 0.0]
  
  # get expected direction of gravity
  g[0] = 2 * (q[1] * q[3] - q[0] * q[2])
  g[1] = 2 * (q[0] * q[1] + q[2] * q[3])
  g[2] = q[0] * q[0] - q[1] * q[1] - q[2] * q[2] + q[3] * q[3]
  
  # compensate accelerometer readings with the expected direction of gravity
  return [acc[0] - g[0], acc[1] - g[1], acc[2] - g[2]]

# time step
dt = 1/100.

# transition_matrix  
F = [[1, dt, 0.5*dt**2], 
     [0,  1,       dt],
     [0,  0,        1]]

# observation_matrix   
H = [0, 0, 1]

# transition_covariance 
Q = [[0.2,    0,      0], 
     [  0,  0.1,      0],
     [  0,    0,  10e-4]]

Q = [[1,    0,      0], 
      [  0,  1,      0],
      [  0,    0,  1]]

# observation_covariance 
#(the value can be calculated based on your sensors datasheet).
R = AccX_Variance

# initial_state_mean
X0 = [0,
      0,
      AccX_Value]

# initial_state_covariance
P0 = [[  0,    0,               0], 
      [  0,    0,               0],
      [  0,    0,   AccX_Variance]]


global filtered_state_means
global filtered_state_covariances
global kf

n_dim_state = 3
filtered_state_means = np.zeros((2, n_dim_state))
filtered_state_covariances = np.zeros((2, n_dim_state, n_dim_state))

kf = KalmanFilter(transition_matrices = F, 
                  observation_matrices = H, 
                  transition_covariance = Q, 
                  observation_covariance = R, 
                  initial_state_mean = X0, 
                  initial_state_covariance = P0)


filtered_state_means[0] = X0
filtered_state_covariances[0] = P0

def kalman_update():
  filtered_state_means[1], filtered_state_covariances[1] = (
        kf.filter_update(
            filtered_state_means[0],
            filtered_state_covariances[0],
            [(AccX_ValueImu1+AccX_ValueImu2)/2.]
        )
  )
  filtered_state_means[0], filtered_state_covariances[0] = filtered_state_means[1], filtered_state_covariances[1]
  

#AccX_estimated = filtered_state_means[1, 2]
#VelX_estimated = filtered_state_means[1, 1]
#PosX_estimated = filtered_state_means[1, 0]


if __name__ == "__main__":
    rospy.init_node('imu_kalman', anonymous=True)
 
#    while not rospy.is_shutdown():
    while True:
        kalman_update()
        print("AccX_Value", (AccX_ValueImu1+AccX_ValueImu2)/2.)
        print("AccX_estimated", filtered_state_means[1, 2])
        print("VelX_estimated", filtered_state_means[1, 1])
        print("PosX_estimated", filtered_state_means[1, 0]) 
        time.sleep(0.1)
#        rate.sleep()
